  
# 核心任务

- name: OpenCV
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
 

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: opencv, tags: "opencv"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
