
#  prepare

- block:
  - name: Installation dependency
    apt: 
      name: build-essential , cmake, git , pkg-config , libgtk-3-dev ,
        libavcodec-dev , libavformat-dev , libswscale-dev , libv4l-dev  ,
        libxvidcore-dev , libx264-dev , libjpeg-dev , libpng-dev , libtiff-dev ,
        gfortran , openexr , libatlas-base-dev , python3-dev , python3-numpy ,
        libtbb2 , libtbb-dev , libdc1394-22-dev , ant
      update_cache: yes

  - name: Clone opencv and opencv_contrib
    shell: |
       git clone https://github.com/opencv/opencv.git
       git clone https://github.com/opencv/opencv_contrib.git
    args:
      cmd:  mkdir ~/opencv_build 
      chdir:  ~/opencv_build/
 

#   Build install

  - name: Build opencv makefile
    shell: |
      cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D OPENCV_GENERATE_PKGCONFIG=ON \
      -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON .. 
     args:
       cmd: mkdir ~/opencv_build/opencv/build
       chdir:  ~/opencv_build/opencv/build/
          

  - name:  Install opencv
    shell: 
      make -j7 && make install